[toolchain]
channel = "1.97.1"
components = ["clippy", "rustfmt"]
targets = [
    "x86_64-unknown-linux-gnu",
    "wasm32-unknown-unknown",
    "aarch64-linux-android",
    "x86_64-linux-android"
]
profile = "minimal"
