[package]
name = "ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[features]
default = []
fullstack = ["dep:api", "api/fullstack", "dioxus/fullstack"]

[dependencies]
dioxus = { version = "0.7.10", default-features = false, features = ["lib"] }
api = { package = "api", path = "../api", optional = true }

[lints]
workspace = true
