[package]
name = "ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[features]
default = []
fullstack = ["dep:api", "api/fullstack", "dioxus/fullstack"]

[dependencies]
dioxus = { workspace = true, features = ["lib"] }
api = { workspace = true, optional = true }

[lints]
workspace = true
