[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[features]
default = []
fullstack = ["dep:dioxus"]
server = ["fullstack", "dioxus/server"]

[dependencies]
dioxus = { workspace = true, features = ["lib", "fullstack"], optional = true }
serde = { workspace = true }

[lints]
workspace = true
