[package]
name = "mobile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[features]
default = ["fullstack"]
fullstack = ["dioxus/fullstack"]
mobile = ["dioxus/mobile"]

[dependencies]
dioxus = { version = "0.7.10", default-features = false, features = ["lib", "launch", "devtools"] }
core = { package = "core", path = "../core" }
ui = { package = "ui", path = "../ui", features = ["fullstack"] }

[lints]
workspace = true
