[package]
name = "starter-mobile"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "starter-mobile"
path = "src/main.rs"

[dependencies]
dioxus = { workspace = true, features = ["mobile"] }
starter-ui = { workspace = true }
starter-core = { workspace = true }
starter-api = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
directories = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = { workspace = true }
ndk-context = { workspace = true }
android_logger = { workspace = true }
