[package]
name = "starter-web-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "starter-web-client"
path = "src/main.rs"

[dependencies]
starter-web = { path = "../web" }

[features]
default = []
web = []
