[package]
name = "fullstack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[features]
default = []
web = ["dioxus/web", "dep:api", "api/fullstack", "ui/fullstack"]
server = ["dioxus/server", "dep:api", "api/server", "ui/fullstack"]

[dependencies]
api = { package = "api", path = "../api", optional = true }
dioxus = { version = "0.7.10", features = ["fullstack"] }
ui = { package = "ui", path = "../ui", default-features = false }

[lints]
workspace = true
