[package]
name = "desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[features]
default = ["fullstack"]
fullstack = ["dioxus/fullstack", "api/fullstack"]
desktop = ["dioxus/desktop"]

[dependencies]
dioxus = { workspace = true, features = ["lib", "launch", "devtools"] }
api = { workspace = true }
core = { workspace = true }
ui = { workspace = true }

[lints]
workspace = true
