[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
api = { workspace = true, features = ["server"] }
dioxus = { workspace = true, features = ["fullstack", "server"] }

[dev-dependencies]
serde_json = { workspace = true }
